spring:
  datasource:
#    user:
#      url: jdbc:mysql://localhost:3306/springboottest?useSSL=false&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    nba:
      url: jdbc:mysql://localhost:3306/nba_total?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  user:
#    mapper-locations: classpath:mapper/user/*.xml
#    type-aliases-package: com.example.SpringBootBatis.bean
#  nba:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.SpringBootBatis.bean
#  ↑可以在mapper.xml中不用写全bean名称
server:
  port: 8888
#config:
#    jwt:
#      # 加密密钥
#      secret: abcdefg1234567
#      # token有效时长
#      expire: 3600
#      # header 名称
#      header: token