spring:
  datasource:
    url: jdbc:sqlite:../nba_spider/nba_total.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: none  # 不自动修改数据库结构
    show-sql: true  # 打印SQL语句到控制台

mybatis:
  #  user:
  #    mapper-locations: classpath:mapper/user/*.xml
  #    type-aliases-package: com.example.SpringBootBatis.bean
  #  nba:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.SpringBootBatis.bean
#  ↑可以在mapper.xml中不用写全bean名称
server:
  port: 8888
#config:
#    jwt:
#      # 加密密钥
#      # token有效时长
#      expire: 3600
#      # header 名称
#      header: token